export const predictions = [
    // Grupo A
    // Alemania vs. Escocia
    { userId: 1, name: "Fabi", matchId: "germany-scotland", teamA: 3, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "germany-scotland", teamA: 2, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "germany-scotland", teamA: 3, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "germany-scotland", teamA: 3, teamB: 0 },
    { userId: 5, name: "David", matchId: "germany-scotland", teamA: 2, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "germany-scotland", teamA: 3, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "germany-scotland", teamA: 2, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "germany-scotland", teamA: 3, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "germany-scotland", teamA: 2, teamB: 0 },
    { userId: 10, name: "Juanmi", matchId: "germany-scotland", teamA: 2, teamB: 0 },
  
    // Hungría vs. Suiza
    { userId: 1, name: "Fabi", matchId: "hungary-switzerland", teamA: 1, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "hungary-switzerland", teamA: 2, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "hungary-switzerland", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "hungary-switzerland", teamA: 1, teamB: 2 },
    { userId: 5, name: "David", matchId: "hungary-switzerland", teamA: 0, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "hungary-switzerland", teamA: 1, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "hungary-switzerland", teamA: 1, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "hungary-switzerland", teamA: 0, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "hungary-switzerland", teamA: 1, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "hungary-switzerland", teamA: 0, teamB: 2 },
  
    // Alemania vs. Hungría
    { userId: 1, name: "Fabi", matchId: "germany-hungary", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "germany-hungary", teamA: 2, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "germany-hungary", teamA: 3, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "germany-hungary", teamA: 3, teamB: 1 },
    { userId: 5, name: "David", matchId: "germany-hungary", teamA: 2, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "germany-hungary", teamA: 2, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "germany-hungary", teamA: 2, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "germany-hungary", teamA: 3, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "germany-hungary", teamA: 2, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "germany-hungary", teamA: 4, teamB: 0 },
  
    // Escocia vs. Suiza
    { userId: 1, name: "Fabi", matchId: "scotland-switzerland", teamA: 1, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "scotland-switzerland", teamA: 1, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "scotland-switzerland", teamA: 1, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "scotland-switzerland", teamA: 0, teamB: 1 },
    { userId: 5, name: "David", matchId: "scotland-switzerland", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "scotland-switzerland", teamA: 1, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "scotland-switzerland", teamA: 2, teamB: 3 },
    { userId: 8, name: "Javi", matchId: "scotland-switzerland", teamA: 1, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "scotland-switzerland", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "scotland-switzerland", teamA: 1, teamB: 3 },
  
    // Suiza vs. Alemania
    { userId: 1, name: "Fabi", matchId: "switzerland-germany", teamA: 1, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "switzerland-germany", teamA: 2, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "switzerland-germany", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "switzerland-germany", teamA: 2, teamB: 4 },
    { userId: 5, name: "David", matchId: "switzerland-germany", teamA: 3, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "switzerland-germany", teamA: 0, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "switzerland-germany", teamA: 0, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "switzerland-germany", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "switzerland-germany", teamA: 0, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "switzerland-germany", teamA: 2, teamB: 3 },
  
    // Escocia vs. Hungría
    { userId: 1, name: "Fabi", matchId: "scotland-hungary", teamA: 1, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "scotland-hungary", teamA: 1, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "scotland-hungary", teamA: 2, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "scotland-hungary", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "scotland-hungary", teamA: 0, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "scotland-hungary", teamA: 2, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "scotland-hungary", teamA: 2, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "scotland-hungary", teamA: 2, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "scotland-hungary", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "scotland-hungary", teamA: 2, teamB: 0 },
  
    // Grupo B
    // España vs. Croacia
    { userId: 1, name: "Fabi", matchId: "spain-croatia", teamA: 2, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "spain-croatia", teamA: 2, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "spain-croatia", teamA: 3, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "spain-croatia", teamA: 2, teamB: 2 },
    { userId: 5, name: "David", matchId: "spain-croatia", teamA: 2, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "spain-croatia", teamA: 1, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "spain-croatia", teamA: 3, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "spain-croatia", teamA: 3, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "spain-croatia", teamA: 3, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "spain-croatia", teamA: 3, teamB: 1 },
  
    // Italia vs. Albania
    { userId: 1, name: "Fabi", matchId: "italy-albania", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "italy-albania", teamA: 3, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "italy-albania", teamA: 3, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "italy-albania", teamA: 1, teamB: 0 },
    { userId: 5, name: "David", matchId: "italy-albania", teamA: 2, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "italy-albania", teamA: 0, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "italy-albania", teamA: 2, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "italy-albania", teamA: 2, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "italy-albania", teamA: 2, teamB: 0 },
    { userId: 10, name: "Juanmi", matchId: "italy-albania", teamA: 1, teamB: 1 },
  
    // Croacia vs. Albania
    { userId: 1, name: "Fabi", matchId: "croatia-albania", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "croatia-albania", teamA: 2, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "croatia-albania", teamA: 2, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "croatia-albania", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "croatia-albania", teamA: 4, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "croatia-albania", teamA: 4, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "croatia-albania", teamA: 3, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "croatia-albania", teamA: 4, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "croatia-albania", teamA: 2, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "croatia-albania", teamA: 2, teamB: 1 },

    // España vs. Italia
    { userId: 1, name: "Fabi", matchId: "spain-italy", teamA: 1, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "spain-italy", teamA: 3, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "spain-italy", teamA: 2, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "spain-italy", teamA: 2, teamB: 1 },
    { userId: 5, name: "David", matchId: "spain-italy", teamA: 1, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "spain-italy", teamA: 2, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "spain-italy", teamA: 2, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "spain-italy", teamA: 3, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "spain-italy", teamA: 2, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "spain-italy", teamA: 3, teamB: 0 },

    // Croacia vs. Italia
    { userId: 1, name: "Fabi", matchId: "croatia-italy", teamA: 1, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "croatia-italy", teamA: 1, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "croatia-italy", teamA: 1, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "croatia-italy", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "croatia-italy", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "croatia-italy", teamA: 2, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "croatia-italy", teamA: 2, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "croatia-italy", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "croatia-italy", teamA: 1, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "croatia-italy", teamA: 2, teamB: 0 },
  
    // Albania vs. España
    { userId: 1, name: "Fabi", matchId: "albania-spain", teamA: 0, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "albania-spain", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "albania-spain", teamA: 0, teamB: 3 },
    { userId: 4, name: "Alberto", matchId: "albania-spain", teamA: 1, teamB: 3 },
    { userId: 5, name: "David", matchId: "albania-spain", teamA: 0, teamB: 3 },
    { userId: 6, name: "Jm", matchId: "albania-spain", teamA: 1, teamB: 5 },
    { userId: 7, name: "Manuel", matchId: "albania-spain", teamA: 1, teamB: 3 },
    { userId: 8, name: "Javi", matchId: "albania-spain", teamA: 0, teamB: 3 },
    { userId: 9, name: "Avelino", matchId: "albania-spain", teamA: 0, teamB: 3 },
    { userId: 10, name: "Juanmi", matchId: "albania-spain", teamA: 1, teamB: 2 },
  
    // Grupo C
    // Eslovenia vs. Dinamarca
    { userId: 1, name: "Fabi", matchId: "slovenia-denmark", teamA: 1, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "slovenia-denmark", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "slovenia-denmark", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "slovenia-denmark", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "slovenia-denmark", teamA: 0, teamB: 3 },
    { userId: 6, name: "Jm", matchId: "slovenia-denmark", teamA: 1, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "slovenia-denmark", teamA: 0, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "slovenia-denmark", teamA: 0, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "slovenia-denmark", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "slovenia-denmark", teamA: 1, teamB: 3 },
  
    // Serbia vs. Inglaterra
    { userId: 1, name: "Fabi", matchId: "serbia-england", teamA: 0, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "serbia-england", teamA: 0, teamB: 3 },
    { userId: 3, name: "Kiko", matchId: "serbia-england", teamA: 2, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "serbia-england", teamA: 0, teamB: 3 },
    { userId: 5, name: "David", matchId: "serbia-england", teamA: 1, teamB: 3 },
    { userId: 6, name: "Jm", matchId: "serbia-england", teamA: 0, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "serbia-england", teamA: 1, teamB: 3 },
    { userId: 8, name: "Javi", matchId: "serbia-england", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "serbia-england", teamA: 1, teamB: 3 },
    { userId: 10, name: "Juanmi", matchId: "serbia-england", teamA: 1, teamB: 2 },
  
    // Eslovenia vs. Serbia
    { userId: 1, name: "Fabi", matchId: "slovenia-serbia", teamA: 1, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "slovenia-serbia", teamA: 1, teamB: 3 },
    { userId: 3, name: "Kiko", matchId: "slovenia-serbia", teamA: 0, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "slovenia-serbia", teamA: 2, teamB: 1 },
    { userId: 5, name: "David", matchId: "slovenia-serbia", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "slovenia-serbia", teamA: 1, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "slovenia-serbia", teamA: 0, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "slovenia-serbia", teamA: 1, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "slovenia-serbia", teamA: 0, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "slovenia-serbia", teamA: 0, teamB: 2 },
  
    // Dinamarca vs. Inglaterra
    { userId: 1, name: "Fabi", matchId: "denmark-england", teamA: 0, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "denmark-england", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "denmark-england", teamA: 1, teamB: 3 },
    { userId: 4, name: "Alberto", matchId: "denmark-england", teamA: 1, teamB: 4 },
    { userId: 5, name: "David", matchId: "denmark-england", teamA: 2, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "denmark-england", teamA: 2, teamB: 2 },
    { userId: 7, name: "Manuel", matchId: "denmark-england", teamA: 2, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "denmark-england", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "denmark-england", teamA: 0, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "denmark-england", teamA: 1, teamB: 3 },
  
    // Inglaterra vs. Eslovenia
    { userId: 1, name: "Fabi", matchId: "england-slovenia", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "england-slovenia", teamA: 4, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "england-slovenia", teamA: 4, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "england-slovenia", teamA: 3, teamB: 2 },
    { userId: 5, name: "David", matchId: "england-slovenia", teamA: 3, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "england-slovenia", teamA: 3, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "england-slovenia", teamA: 2, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "england-slovenia", teamA: 2, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "england-slovenia", teamA: 3, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "england-slovenia", teamA: 3, teamB: 0 },
  
    // Dinamarca vs. Serbia
    { userId: 1, name: "Fabi", matchId: "denmark-serbia", teamA: 1, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "denmark-serbia", teamA: 2, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "denmark-serbia", teamA: 2, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "denmark-serbia", teamA: 1, teamB: 2 },
    { userId: 5, name: "David", matchId: "denmark-serbia", teamA: 2, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "denmark-serbia", teamA: 1, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "denmark-serbia", teamA: 2, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "denmark-serbia", teamA: 2, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "denmark-serbia", teamA: 2, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "denmark-serbia", teamA: 2, teamB: 0 },
  
    // Grupo D
    // Polonia vs. Paises Bajos
    { userId: 1, name: "Fabi", matchId: "poland-netherlands", teamA: 0, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "poland-netherlands", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "poland-netherlands", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "poland-netherlands", teamA: 1, teamB: 1 },
    { userId: 5, name: "David", matchId: "poland-netherlands", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "poland-netherlands", teamA: 0, teamB: 2 },
    { userId: 7, name: "Manuel", matchId: "poland-netherlands", teamA: 1, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "poland-netherlands", teamA: 1, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "poland-netherlands", teamA: 0, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "poland-netherlands", teamA: 0, teamB: 2 },
  
    // Austria vs. Francia
    { userId: 1, name: "Fabi", matchId: "austria-france", teamA: 0, teamB: 4 },
    { userId: 2, name: "Julen", matchId: "austria-france", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "austria-france", teamA: 0, teamB: 3 },
    { userId: 4, name: "Alberto", matchId: "austria-france", teamA: 1, teamB: 3 },
    { userId: 5, name: "David", matchId: "austria-france", teamA: 0, teamB: 3 },
    { userId: 6, name: "Jm", matchId: "austria-france", teamA: 1, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "austria-france", teamA: 0, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "austria-france", teamA: 0, teamB: 4 },
    { userId: 9, name: "Avelino", matchId: "austria-france", teamA: 0, teamB: 3 },
    { userId: 10, name: "Juanmi", matchId: "austria-france", teamA: 1, teamB: 3 },
  
    // Polonia vs. Austria
    { userId: 1, name: "Fabi", matchId: "poland-austria", teamA: 1, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "poland-austria", teamA: 0, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "poland-austria", teamA: 2, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "poland-austria", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "poland-austria", teamA: 2, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "poland-austria", teamA: 0, teamB: 2 },
    { userId: 7, name: "Manuel", matchId: "poland-austria", teamA: 2, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "poland-austria", teamA: 2, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "poland-austria", teamA: 0, teamB: 0 },
    { userId: 10, name: "Juanmi", matchId: "poland-austria", teamA: 1, teamB: 2 },
  
    // Paises Bajos vs. Francia
    { userId: 1, name: "Fabi", matchId: "netherlands-france", teamA: 1, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "netherlands-france", teamA: 1, teamB: 3 },
    { userId: 3, name: "Kiko", matchId: "netherlands-france", teamA: 1, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "netherlands-france", teamA: 1, teamB: 2 },
    { userId: 5, name: "David", matchId: "netherlands-france", teamA: 3, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "netherlands-france", teamA: 0, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "netherlands-france", teamA: 2, teamB: 3 },
    { userId: 8, name: "Javi", matchId: "netherlands-france", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "netherlands-france", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "netherlands-france", teamA: 0, teamB: 2 },
  
    // Paises Bajos vs. Austria
    { userId: 1, name: "Fabi", matchId: "netherlands-austria", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "netherlands-austria", teamA: 2, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "netherlands-austria", teamA: 3, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "netherlands-austria", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "netherlands-austria", teamA: 2, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "netherlands-austria", teamA: 2, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "netherlands-austria", teamA: 2, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "netherlands-austria", teamA: 2, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "netherlands-austria", teamA: 3, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "netherlands-austria", teamA: 2, teamB: 2 },
  
    // Francia vs. Polonia
    { userId: 1, name: "Fabi", matchId: "france-poland", teamA: 1, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "france-poland", teamA: 2, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "france-poland", teamA: 3, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "france-poland", teamA: 1, teamB: 0 },
    { userId: 5, name: "David", matchId: "france-poland", teamA: 2, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "france-poland", teamA: 3, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "france-poland", teamA: 3, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "france-poland", teamA: 2, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "france-poland", teamA: 2, teamB: 0 },
    { userId: 10, name: "Juanmi", matchId: "france-poland", teamA: 4, teamB: 0 },
  
    // Grupo E
    // Rumanía vs. Ucrania
    { userId: 1, name: "Fabi", matchId: "romania-ukraine", teamA: 0, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "romania-ukraine", teamA: 0, teamB: 3 },
    { userId: 3, name: "Kiko", matchId: "romania-ukraine", teamA: 0, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "romania-ukraine", teamA: 1, teamB: 2 },
    { userId: 5, name: "David", matchId: "romania-ukraine", teamA: 0, teamB: 3 },
    { userId: 6, name: "Jm", matchId: "romania-ukraine", teamA: 1, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "romania-ukraine", teamA: 1, teamB: 3 },
    { userId: 8, name: "Javi", matchId: "romania-ukraine", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "romania-ukraine", teamA: 0, teamB: 3 },
    { userId: 10, name: "Juanmi", matchId: "romania-ukraine", teamA: 0, teamB: 3 },
  
    // Bélgica vs. Eslovaquia
    { userId: 1, name: "Fabi", matchId: "belgium-slovakia", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "belgium-slovakia", teamA: 5, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "belgium-slovakia", teamA: 3, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "belgium-slovakia", teamA: 2, teamB: 2 },
    { userId: 5, name: "David", matchId: "belgium-slovakia", teamA: 2, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "belgium-slovakia", teamA: 4, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "belgium-slovakia", teamA: 3, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "belgium-slovakia", teamA: 3, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "belgium-slovakia", teamA: 4, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "belgium-slovakia", teamA: 2, teamB: 0 },
  
    // Eslovaquia vs. Ucrania
    { userId: 1, name: "Fabi", matchId: "slovakia-ukraine", teamA: 0, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "slovakia-ukraine", teamA: 1, teamB: 3 },
    { userId: 3, name: "Kiko", matchId: "slovakia-ukraine", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "slovakia-ukraine", teamA: 1, teamB: 1 },
    { userId: 5, name: "David", matchId: "slovakia-ukraine", teamA: 0, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "slovakia-ukraine", teamA: 0, teamB: 2 },
    { userId: 7, name: "Manuel", matchId: "slovakia-ukraine", teamA: 1, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "slovakia-ukraine", teamA: 1, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "slovakia-ukraine", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "slovakia-ukraine", teamA: 1, teamB: 2 },
  
    // Bélgica vs. Rumanía
    { userId: 1, name: "Fabi", matchId: "belgium-romania", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "belgium-romania", teamA: 3, teamB: 0 },
    { userId: 3, name: "Kiko", matchId: "belgium-romania", teamA: 2, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "belgium-romania", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "belgium-romania", teamA: 3, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "belgium-romania", teamA: 1, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "belgium-romania", teamA: 2, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "belgium-romania", teamA: 3, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "belgium-romania", teamA: 3, teamB: 0 },
    { userId: 10, name: "Juanmi", matchId: "belgium-romania", teamA: 3, teamB: 1 },
  
    // Eslovaquia vs. Rumanía
    { userId: 1, name: "Fabi", matchId: "slovakia-romania", teamA: 2, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "slovakia-romania", teamA: 2, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "slovakia-romania", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "slovakia-romania", teamA: 1, teamB: 0},
    { userId: 5, name: "David", matchId: "slovakia-romania", teamA: 1, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "slovakia-romania", teamA: 0, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "slovakia-romania", teamA: 2, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "slovakia-romania", teamA: 1, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "slovakia-romania", teamA: 0, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "slovakia-romania", teamA: 1, teamB: 1 },
  
    // Ucrania vs. Bélgica
    { userId: 1, name: "Fabi", matchId: "ukraine-belgium", teamA: 1, teamB: 3 },
    { userId: 2, name: "Julen", matchId: "ukraine-belgium", teamA: 1, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "ukraine-belgium", teamA: 1, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "ukraine-belgium", teamA: 2, teamB: 2 },
    { userId: 5, name: "David", matchId: "ukraine-belgium", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "ukraine-belgium", teamA: 0, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "ukraine-belgium", teamA: 1, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "ukraine-belgium", teamA: 2, teamB: 3 },
    { userId: 9, name: "Avelino", matchId: "ukraine-belgium", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "ukraine-belgium", teamA: 1, teamB: 2 },
  
    // Grupo F
    // Turquía vs. Georgia
    { userId: 1, name: "Fabi", matchId: "turkiye-georgia", teamA: 2, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "turkiye-georgia", teamA: 2, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "turkiye-georgia", teamA: 3, teamB: 0 },
    { userId: 4, name: "Alberto", matchId: "turkiye-georgia", teamA: 2, teamB: 0 },
    { userId: 5, name: "David", matchId: "turkiye-georgia", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "turkiye-georgia", teamA: 1, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "turkiye-georgia", teamA: 1, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "turkiye-georgia", teamA: 2, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "turkiye-georgia", teamA: 2, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "turkiye-georgia", teamA: 3, teamB: 0 },
  
    // Portugal vs. Checa
    { userId: 1, name: "Fabi", matchId: "portugal-czech republic", teamA: 2, teamB: 0 },
    { userId: 2, name: "Julen", matchId: "portugal-czech republic", teamA: 3, teamB: 1 },
    { userId: 3, name: "Kiko", matchId: "portugal-czech republic", teamA: 3, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "portugal-czech republic", teamA: 3, teamB: 1 },
    { userId: 5, name: "David", matchId: "portugal-czech republic", teamA: 2, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "portugal-czech republic", teamA: 3, teamB: 0 },
    { userId: 7, name: "Manuel", matchId: "portugal-czech republic", teamA: 3, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "portugal-czech republic", teamA: 3, teamB: 1 },
    { userId: 9, name: "Avelino", matchId: "portugal-czech republic", teamA: 3, teamB: 0 },
    { userId: 10, name: "Juanmi", matchId: "portugal-czech republic", teamA: 3, teamB: 0 },
  
    // Georgia vs. Checa
    { userId: 1, name: "Fabi", matchId: "georgia-czech republic", teamA: 1, teamB: 1 },
    { userId: 2, name: "Julen", matchId: "georgia-czech republic", teamA: 2, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "georgia-czech republic", teamA: 1, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "georgia-czech republic", teamA: 0, teamB: 2 },
    { userId: 5, name: "David", matchId: "georgia-czech republic", teamA: 1, teamB: 0 },
    { userId: 6, name: "Jm", matchId: "georgia-czech republic", teamA: 0, teamB: 2 },
    { userId: 7, name: "Manuel", matchId: "georgia-czech republic", teamA: 1, teamB: 0 },
    { userId: 8, name: "Javi", matchId: "georgia-czech republic", teamA: 1, teamB: 0 },
    { userId: 9, name: "Avelino", matchId: "georgia-czech republic", teamA: 2, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "georgia-czech republic", teamA: 0, teamB: 2 },
  
    // Turquía vs. Portugal
    { userId: 1, name: "Fabi", matchId: "turkiye-portugal", teamA: 1, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "turkiye-portugal", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "turkiye-portugal", teamA: 2, teamB: 1 },
    { userId: 4, name: "Alberto", matchId: "turkiye-portugal", teamA: 2, teamB: 3 },
    { userId: 5, name: "David", matchId: "turkiye-portugal", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "turkiye-portugal", teamA: 1, teamB: 4 },
    { userId: 7, name: "Manuel", matchId: "turkiye-portugal", teamA: 0, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "turkiye-portugal", teamA: 1, teamB: 3 },
    { userId: 9, name: "Avelino", matchId: "turkiye-portugal", teamA: 1, teamB: 2 },
    { userId: 10, name: "Juanmi", matchId: "turkiye-portugal", teamA: 2, teamB: 2 },

    // Checa vs. Turquia
    { userId: 1, name: "Fabi", matchId: "czech republic-turkiye", teamA: 2, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "czech republic-turkiye", teamA: 2, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "czech republic-turkiye", teamA: 0, teamB: 2 },
    { userId: 4, name: "Alberto", matchId: "czech republic-turkiye", teamA: 1, teamB: 1 },
    { userId: 5, name: "David", matchId: "czech republic-turkiye", teamA: 1, teamB: 1 },
    { userId: 6, name: "Jm", matchId: "czech republic-turkiye", teamA: 3, teamB: 1 },
    { userId: 7, name: "Manuel", matchId: "czech republic-turkiye", teamA: 0, teamB: 1 },
    { userId: 8, name: "Javi", matchId: "czech republic-turkiye", teamA: 1, teamB: 2 },
    { userId: 9, name: "Avelino", matchId: "czech republic-turkiye", teamA: 0, teamB: 1 },
    { userId: 10, name: "Juanmi", matchId: "czech republic-turkiye", teamA: 1, teamB: 2 },
  
    // Georgia vs. Portugal
    { userId: 1, name: "Fabi", matchId: "georgia-portugal", teamA: 1, teamB: 2 },
    { userId: 2, name: "Julen", matchId: "georgia-portugal", teamA: 0, teamB: 2 },
    { userId: 3, name: "Kiko", matchId: "georgia-portugal", teamA: 1, teamB: 3 },
    { userId: 4, name: "Alberto", matchId: "georgia-portugal", teamA: 0, teamB: 2 },
    { userId: 5, name: "David", matchId: "georgia-portugal", teamA: 1, teamB: 2 },
    { userId: 6, name: "Jm", matchId: "georgia-portugal", teamA: 0, teamB: 2 },
    { userId: 7, name: "Manuel", matchId: "georgia-portugal", teamA: 1, teamB: 2 },
    { userId: 8, name: "Javi", matchId: "georgia-portugal", teamA: 1, teamB: 3 },
    { userId: 9, name: "Avelino", matchId: "georgia-portugal", teamA: 1, teamB: 3 },
    { userId: 10, name: "Juanmi", matchId: "georgia-portugal", teamA: 0, teamB: 5 },
  ];


  export const users = [
    { id: 1, name: "Fabi" },
    { id: 2, name: "Julen" },
    { id: 3, name: "Kiko" },
    { id: 4, name: "Alberto" },
    { id: 5, name: "David" },
    { id: 6, name: "Jm" },
    { id: 7, name: "Manuel" },
    { id: 8, name: "Javi" },
    { id: 9, name: "Avelino" },
    { id: 10, name: "Juanmi" },
  ];
  
  